// MIT/Apache2 License

use regex::Regex;
use std::ffi::OsStr;

#[inline]
pub fn corrections(body: String, fname: &OsStr) -> String {
  let re1 = Regex::new(r"\bStr\b").unwrap();
  let re2 = Regex::new(r"\bChar\b").unwrap();
  let re3 = Regex::new(r"\bBool\b").unwrap();
  let re4 = Regex::new(r"\bVoid\b").unwrap();

  let body = re1.replace_all(&body, "String");
  let body = re2.replace_all(&body, "bool");
  let body = re3.replace_all(&body, "cty::c_char");
  let mut body = re4.replace_all(&body, "u8");

  format!(
    "// This file was automatically generated by the flutterbug_generator crate from {:?}.
// This file is considered to be dual-licensed under the MIT and Apache 2.0 licenses.

{}",
    fname, body
  )
}
